id: I17627160
legacy_id: P009382
ocr_import_info:
  bdrc_scan_id: W4CZ74409
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T07:54:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:05:34.105670+00:00'
last_modified: 2022-09-04 05:05:44.132464
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74409
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74409
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྲེང་བ་གཉིས་ཀྱི་ཆོ་གའི་ངག་འདོན་གྱི་རིམ་པ་ཁྲིགས་སུ་སྡེབ་པ་མཐོང་བ་དོན་གྲུབ།
  author: སྐྱིད་ཤོད་ཞབས་དྲུང་ངག་དབང་བསྟན་འཛིན་འཕྲིན་ལས།
statistics:
  ocr_word_mean_confidence_index: 0.6887705378129195
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I4CZ74411:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74411
      total_pages: 271
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74411.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.6887705378129195
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
